spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springboot_test?useSSL=true&characterEncoding=utf-8
  redis:
    database: 5
    host: 192.168.1.22
    port: 6379
    jedis:
      pool:
        max-active: 1000
        min-idle: 10
        max-idle: 500
        max-wait: 5000ms
    timeout: 10000ms